### PR TITLE
Potential fix for #1558 and feature proposal

### LINKED ISSUE #1558: 1.13.2 JEI is loaded too many times on reload.
JEI: 5.0.0.20
Forge: 25.0.145

When running the `/reload` command JEI seems to rebuild it's data twice. I don't think this was intended. 

```
[16:17:23.823] [Client thread/INFO] [me.je.st.ClientLifecycleHandler/]: Restarting JEI.
[16:17:23.823] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Starting JEI...
[16:17:23.920] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient list...
[16:17:23.921] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient list took 1.434 ms
[16:17:23.921] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient filter...
[16:17:24.136] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient filter took 214.9 ms
[16:17:24.136] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building bookmarks...
[16:17:24.136] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building bookmarks took 92.84 ?s
[16:17:24.137] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building recipe registry...
[16:17:24.157] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building recipe registry took 20.11 ms
[16:17:24.157] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building runtime...
[16:17:24.159] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building runtime took 964.0 ?s
[16:17:24.166] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Starting JEI took 343.0 ms
[16:17:24.166] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Starting JEI...
[16:17:24.233] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient list...
[16:17:24.234] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient list took 1.208 ms
[16:17:24.234] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient filter...
[16:17:24.378] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building ingredient filter took 143.6 ms
[16:17:24.379] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building bookmarks...
[16:17:24.379] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building bookmarks took 91.26 ?s
[16:17:24.379] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building recipe registry...
[16:17:24.396] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building recipe registry took 16.51 ms
[16:17:24.396] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building runtime...
[16:17:24.396] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Building runtime took 235.5 ?s
[16:17:24.398] [Client thread/INFO] [me.je.ut.LoggedTimer/]: Starting JEI took 231.1 ms
```

### PR DESCRIPTION
**Pull request by Speiger**
- Fixed: #1558 (Basically does not allow to register reloads multiple times.
- Added: Delayed reload (5 seconds) so if other mods have custom recipe Syncers that their Recipes are also present before JEI decides to reload its data, since all data has to be present when JEI loads its internals.

### CODE REVIEW

**Comment by Speiger** [comment]
removing stale?

**Comment by Speiger** [comment]
also @mezz what about accepting the patch or requesting changes if you dont want the delayed feature?

**Comment by mezz** [comment]
Thanks for contributing!
A solution to this problem should not include timers, they are not performant or reliable.
I am thinking of making JEI plugin methods return futures, so that they can delay as long as necessary to get their state updated.

**Comment by Speiger** [comment]
Yeah that's a better solution then mine.
Then should I close this or leave this open as "Reminder"?

**Comment by mezz** [comment]
I think it is fine to leave this open until the issue is fixed.

**Comment by Speiger** [comment]
@mezz this should become a priorty since bigger mods start porting now. And if they want to support reloadable recipes (and not static recipes which is 1.12 or older) this will become important.

**Comment by Speiger** [comment]
Not stale. Reminder that this still exists.

**Comment by Speiger** [comment]
Anti stale

**Comment by Speiger** [comment]
unstale mode activated!

**Comment by Speiger** [comment]
?

**Pull request closed without merging**
