### PR TITLE
Update to support the breaking changes in forge

### PR DESCRIPTION
**Pull request by pupnewfster**
This PR bumps the min forge version to 41.0.94.  I am not quite happy with how I got key bindings working and being registered but I wasn't really sure of a better way to handle it (I am also not 100% positive I didn't somehow break fabric but in theory it should work and compile still)

### CODE REVIEW

**Comment by sekwah41** [comment]
Given the changes you've done the most likely place, you would be to break fabric I think would be the keybinds. I know when I was tinkering with forge its quite easy to have code that compiles but just doesn't register the keybinds as it's not called right.

Otherwise, if it compiles it looks like most of the rest should be fine.

If you can just give it a quick test to see if the keybinds register properly on fabric.

**Comment by pupnewfster** [comment]
I have never been able to get jei to compile on fabric even with fresh clones. I always end up having to comment it out in the settings gradle in order to build and test forge. But given I am just adding consumer's to method signatures I don't see how it could break.

**Comment by mezz** [comment]
This looks good to me, it doesn't really change how the Fabric keybinds work at all.

**Comment by mezz** [comment]
Thank you!

**Pull request merged**
