### PR TITLE
update ja_jp.lang

### PR DESCRIPTION
**Pull request by koh-gh**

### CODE REVIEW

**Comment by Greg-21** [comment]
I would just like to say that some time ago in commit b56816d8baa06eed47d015d37411986bbffd9b74 were changed several descriptions. So if you want, you can take a look at them, while you're at it :)

**Comment by Greg-21** [comment]
I would just like to say that some time ago in commit b56816d8baa06eed47d015d37411986bbffd9b74 were changed several descriptions. So if you want, you can take a look at them, while you're at it :)

**Comment by mezz** [comment]
Thank you!

**Comment by koh-gh** [comment]
> I would just like to say that some time ago in commit b56816d were changed several descriptions. So if you want, you can take a look at them, while you're at it :)

Oh, I missed it, thank you.

**Comment by Greg-21** [comment]
@koh-gh I'm glad to hear that :)

**Pull request merged**
