### PR TITLE
minor fix

### PR DESCRIPTION
**Pull request by sokratis12GR**

### CODE REVIEW

**Comment by mezz** [comment]
Thank you!

@ELChris414 do you agree with this change?

**Comment by ttofis** [comment]
I tottaly agree, and thank you Sokratis for spotting this mistake that i made! (Σε ευχαριστώ φίλε!)

**Comment by ttofis** [comment]
And mezz just so you understand the fix that he made, and i am really thankful for him doing since i told you, i translated it too quickly, is the gender of the word and also capitalisation

**Comment by mezz** [comment]
Sounds good, thank you both!

**Pull request merged**
