### PR TITLE
Updated texture of focused button state (branch 1.15)

### PR DESCRIPTION
**Pull request by Greg-21**
The same changes as in #2052, but this time for 1.15.

### CODE REVIEW

**Comment by mezz** [comment]
Thanks!

**Comment by Greg-21** [comment]
Does your changelog generator take the PR name or the commit message? IIRC it was taking the commit message, but I'm not sure.

**Comment by mezz** [comment]
It takes the commit message. 
Github auto-changed the PR title to match the commit message. Kind of a nice feature but not really necessary for the changelog to work.

**Comment by Greg-21** [comment]
Ah, okay. Thank you for the clarification.

**Pull request merged**
