### PR TITLE
Fix up for forge 1.14.4-28.0.45+(supercedes and includes #1653)

### PR DESCRIPTION
**Pull request by itsmeow**
This will work after the breaking changes of Forge 28.0.45 (events were moved) - hopefully this saves a few minutes, lol.

### CODE REVIEW

**Comment by mezz** [comment]
Thanks for contributing!
I don't think this solution is correct, it seems to be using the input ingredient twice and ignoring the potion input ingredient.
I have submitted a fix here: https://github.com/mezz/JustEnoughItems/commit/054ef7fb37ad3019f31947807142ba95e0457be4

**Comment by itsmeow** [comment]
Alright thanks, (although it isn't my fix, that was from #1653). Thanks for the update.

**Comment by itsmeow** [comment]
Hold on, this doesn't work on 28.0.45, which introduced breaking changes to Forge.

**Comment by ProsperCraft** [comment]
We really need to make the hop over to .45 because of the forge breaking changes, several mods have updated there and only work with .45 and to continue testing we need to go there.

**Comment by mezz** [comment]
I am unable to update to Forge .45 because of a ForgeGradle issue with that version of Forge in dev. I get an exception during this stage of setting up the project:
```
Running 'SideStripper'
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.tree.ClassNode.<init>(ClassNode.java:164)
	at org.objectweb.asm.tree.ClassNode.<init>(ClassNode.java:150)
	at net.minecraftforge.gradle.mcp.function.SideAnnotationStripperFunction.execute(SideAnnotationStripperFunction.java:104)
```
When Lex or cpw fix that, I will be able to update.

**Comment by itsmeow** [comment]
This PR is basically just an update to .45 aside from the Brewing stand thing, so without that it would function as a fix. I haven't seen that error, but I use eclipse so probably that's why. Thanks for all!

**Comment by mezz** [comment]
Unfortunately I think this is caused by a ForgeGradle update a few days ago, and I cannot downgrade it because it's not really versioned. It should work for you as long as you don't update the Forge version or ForgeGradle.

**Comment by mezz** [comment]
This also means my build system will not be able to build it, even if you or I submit a fix :/. Unfortunately we will just have to wait a little bit for the fix.

**Comment by mezz** [comment]
I submitted an issue here: https://github.com/MinecraftForge/ForgeGradle/issues/611

**Pull request closed without merging**
