### PR TITLE
Fix JEI's icon in Mod Menu

### PR DESCRIPTION
**Pull request by Jab125**

### CODE REVIEW

**Comment by Jab125** [comment]
I can't sign the CLA because nothing is loading on its page

**Comment by Spinoscythe** [comment]
@Jab125 It's working for me

**Comment by mezz** [comment]
Thank you for contributing!
The CLA page can take a long time to load sometimes, sorry. Try leaving the page open and come back to it later

**Comment by mezz** [comment]
This has been fixed in https://github.com/mezz/JustEnoughItems/pull/3263

**Pull request closed without merging**
