### PR TITLE
Banish the access transformers back to the hell they came from

### PR DESCRIPTION
**Pull request by shadowfacts**

### CODE REVIEW

**Comment by mezz** [comment]
Honestly this is a lot just to get around ATs.
What's so evil about the ATs compared to this? :/

**Comment by asiekierka** [comment]
Aren't access transformers faster than reflection?

**Comment by Vexatos** [comment]
@asiekierka A lot faster.

**Comment by mezz** [comment]
Sorry @shadowfacts, I appreciate the effort though.

**Pull request closed without merging**
