### PR TITLE
Politics in kid's game

### PR DESCRIPTION
**Pull request by KBenster**
What would you think if curseforge started spreading "Trump 2020"?

Impacts overall quality of mod, is what I'm saying.

### CODE REVIEW

**Comment by lordmahan** [comment]
LOL

**Comment by ghost** [comment]
This code is seriously still here? Issues were put 5 months ago, and this is a minecraft mod...

**Comment by mezz** [comment]
Huh? This code path hasn't been active since the election. 
I know you want Trump to win but you have to set your computer's clock to 2021.

**Comment by mezz** [comment]
Definitely want to remove this code but it's not a high priority since it's inactive. 
If you can change up the PR to be less bratty I'll gladly merge it lol

**Comment by KBenster** [comment]
Sounds like cope, Bernie2020

**Pull request closed without merging**
