### PR TITLE
Update zh_TW

### PR DESCRIPTION
**Pull request by NatsuArashi**

### CODE REVIEW

**Comment by mezz** [comment]
Thank you!

@HeartyYF do these changes look good to you?

**Review by 3TUSK — APPROVED** [review]

**Comment by 3TUSK** [comment]
@mezz I can tell that @NatsuArashi's translation is far more better than @HeartyYF's... I even considered to adapt some of them to the simplified one (i.e. `zh_cn`).

**Review by HeartyYF — APPROVED** [review]

**Comment by HeartyYF** [comment]
3T do have a point, he is much better than me :-)But surely I wouldn't stop translating XD

**Comment by mezz** [comment]
Thanks everyone

**Comment by NatsuArashi** [comment]
@HeartyYF Keep translating plz~ :D

**Pull request merged**
