### PR TITLE
Update to latest forge and MCP Snapshot 20160421

### PR DESCRIPTION
**Pull request by Craiel**
Hey hey,

not sure if you maybe want this change or not but i figured i just send it and see.
I've been running this locally since i am working on a couple other mods as well that have recently merged to the new MCP + Forge so i am running this in dev environment.

It might be too early to take yet but ill leave that up to your consideration :)

### CODE REVIEW

**Comment by mezz** [comment]
Thanks, this seems useful. Did you close it by accident?

**Comment by Craiel** [comment]
Yeah was meant to close another request, sorry about that

**Comment by shadowfacts** [comment]
o_O, you updated the Gradle wrapper from 2.3 to 2.7 but the latest version is 2.12. wat.

**Comment by GirafiStudios** [comment]
Forge MDK is using Gradle 2.7 currently. Probably why he choose that version.

**Comment by shadowfacts** [comment]
ForgeGradle works exactly the same on 2.12, there's really no reason to be using an outdated version.

**Comment by mezz** [comment]
Gradle's kinda shit so I'm happy to stick to the version Forge is using. 
Uncharted territory with Gradle = mezz retires from modding out of extreme frustration.

**Comment by Craiel** [comment]
Yeah just chose the same as all the other mods and MDK had lying around, i'd be good with any version tbh just thought it's good to go with the masses lol

**Comment by jriwanek** [comment]
Honestly, you should _atleast_ be using 2.4:

https://gradle.org/gradle-2-4-the-fastest-yet/

Forge itself uses somewhere between 2.7 and 2.12 iirc (depending on which subproject), the MDK uses 2.7 as a baseline, if one uses eclipse mars then it likes _atleast_ 2.9 for all features and 2.12 if you happen to update buildship.

Just FYI's, But yeah, I've been using 2.12 in my own stuff and had no problems.

Edit: Yes, I'm aware you updated to 2.7 (This is just notes for anybody else who happens upon it)

**Pull request merged**
