### PR TITLE
fix fluid rendering in bookmark preview

### PR DESCRIPTION
**Pull request by vfyjxf**
eb26f5295e14f66ec6b47ae7b733c581

### CODE REVIEW

**Comment by vfyjxf** [comment]
improve amount display

**Comment by mezz** [comment]
I cleaned this up to merge it, but I'm having a difficult time figuring out how to make the amount render in a way that doesn't expand outside of the fluid.
Either we can render it very small (hard to read), or it overflows...

Screenshot 2024-08-23 at 10 03 26 PM

**Comment by vfyjxf** [comment]
We just need to make his overflow as inconspicuous as possible and keep it readable

**Comment by mezz** [comment]
I think I want to add a "marquee" text for this case, so that the text always fits in a small area but it can scroll over time to show all the information.

**Comment by mezz** [comment]
I think I want to add a "marquee" text for this case, so that the text always fits in a small area but it can scroll over time to show all the information.

**Comment by vfyjxf** [comment]
> marquee

I think marquee text might not be appropriate, at least not for text that goes beyond just a little, where the player might want to determine the exact value at a glance.

**Comment by vfyjxf** [comment]
> I think I want to add a "marquee" text for this case, so that the text always fits in a small area but it can scroll over time to show all the information.

I think marquee text might not be appropriate, at least not for text that goes beyond just a little, where the player might want to determine the exact value at a glance.

**Pull request closed without merging**
