### PR TITLE
Translating to Bulgarian

### PR DESCRIPTION
**Pull request by sokratis12GR**
I will be finishing this part by part, Please don't merge yet

### CODE REVIEW

**Comment by mezz** [comment]
Ok, just let me know when you are finished. Thanks!

**Comment by sokratis12GR** [comment]
@mezz You can merge now ;)

**Comment by TehNut** [comment]
Why is there a bunch not translated?

**Comment by sokratis12GR** [comment]
fuuu, the last part didn't safe u.u

**Comment by sokratis12GR** [comment]
Done

**Comment by TehNut** [comment]
What about lines 72, 73, and 74?

**Comment by RedNesto** [comment]
_Comes descreetly_
Double '=' [here](https://github.com/mezz/JustEnoughItems/pull/406/files#diff-b28a62a299bfe776bf09eb479786ccb5R70)

**Comment by sokratis12GR** [comment]
fixed ^^

**Comment by RedNesto** [comment]
Oh, and a lonely 'T' [there](https://github.com/mezz/JustEnoughItems/pull/406/files#diff-b28a62a299bfe776bf09eb479786ccb5R18)

**Comment by sokratis12GR** [comment]
k

**Comment by RedNesto** [comment]
Wow, you're reactive c:

**Comment by sokratis12GR** [comment]
If I do something I do it right, or fixing it immediately :D

**Comment by RedNesto** [comment]
Always watching what you post, like me.

[Default](https://github.com/mezz/JustEnoughItems/pull/406/files#diff-b28a62a299bfe776bf09eb479786ccb5R31), [Mode](https://github.com/mezz/JustEnoughItems/pull/406/files#diff-b28a62a299bfe776bf09eb479786ccb5R36), [Interface](https://github.com/mezz/JustEnoughItems/pull/406/files#diff-b28a62a299bfe776bf09eb479786ccb5R43) and [Debug Mode](https://github.com/mezz/JustEnoughItems/pull/406/files#diff-b28a62a299bfe776bf09eb479786ccb5R73) aren't translated, is it inteded ?

**Comment by sokratis12GR** [comment]
yep, no actual meaning in bulgarian

**Comment by RedNesto** [comment]
Ah ok, I see nothing wrong now ;)

**Comment by sokratis12GR** [comment]
oops `Mode` is translatable just `Debug Mode` isn't

**Comment by mezz** [comment]
Thank you!
If you have more changes, feel free to make a new pull request.

**Pull request merged**
