### PR TITLE
Update de_DE.lang

### PR DESCRIPTION
**Pull request by copyyy**
Just minor changes, didn't want to include following ideas, maybe you / the translators had good reasons to translate it like you/they did:
29: "Gibt Items" instead of "/give Items" | Translation and explanation instead of "command"
52: "Fügt zufällige Zeichenfolgen hinzu, welche bei der Fehlersuche und -behebung helfen." | Could be confusing. People could think they should turn it on to help developing JEI, but I guess it's just an offline debug thing and nothing gets send to the developer in case of errors?!
61-64: "Strg+Klick" instead of "Strg-Klick" | just looks better imo

### CODE REVIEW

**Comment by wlhlm** [comment]
> 29: "Gibt Items" instead of "/give Items" | Translation and explanation instead of "command"

The English version has `config.jei.mode.cheatItemsEnabled.comment=/give items instead of showing the recipe.` Which, I agree with you, is a weird phrase.

> 52: "Fügt zufällige Zeichenfolgen hinzu, welche bei der Fehlersuche und -behebung helfen." | Could be confusing. People could think they should turn it on to help developing JEI, but I guess it's just an offline debug thing and nothing gets send to the developer in case of errors?!

Yeah. Maybe add something like "Nur für Entwickler bestimmt"

> 61-64: "Strg+Klick" instead of "Strg-Klick" | just looks better imo

Modifier-MouseButton is used in many other mod's translations. That's why I went with that.

**Comment by mezz** [comment]
`config.jei.mode.cheatItemsEnabled.comment` in English can be improved but I'm not sure what it should be.

**Comment by labpaw** [comment]
@mezz I noticed this too. Maybe "Give items instead of showing the recipe" can be better here?

**Comment by mezz** [comment]
Oh I see. That sounds better.

**Comment by mezz** [comment]
@copyyy can you respond to @wlhlm's recommendations?

**Comment by copyyy** [comment]
Oh right, sorry. There you go

**Comment by mezz** [comment]
Thanks! @wlhlm does this look good now?

**Comment by wlhlm** [comment]
:+1: :shipit:

Maybe squash the commits?

**Pull request merged**
