### PR TITLE
Fix #2875 and make RecipeTransferErrorTooltip display correctly.

### LINKED ISSUE #2875: [Bug]: Unexpected highlighting appears in the Recipe gui.
### Steps to Reproduce the Bug

First open Recipe Gui (such as Crafting Table Recipe), and then place the mouse in the upper left corner of the screen in an area that approximates the size of a composite grid of Crafting Table.

### Expected Behavior

Do not show those highlights.

### Actual Behavior

There is an unexpected highlight in the grid showing the recipe.

### Mod Pack URL (Optional)

_No response_

### Mod Pack Version (Optional)

_No response_

### Extra Notes (Optional)

It looks like this:

image

### latest.log

https://gist.github.com/vfyjxf/2dd0df52bafaaed54d521931358b8e7d

### PR DESCRIPTION
**Pull request by vfyjxf**
See the title and below is a comparison of before and after.
| Before|After | 
|------- | ----- | 
| tooltip1| tooltip2  | 
|highlight1| highlight2|

### CODE REVIEW

**Comment by vfyjxf** [comment]
Also I'm not sure why jei is drawing highlight twice. they are [RecipeSlots](https://github.com/mezz/JustEnoughItems/blob/1.18/Common/src/main/java/mezz/jei/common/gui/ingredients/RecipeSlots.java#L35-L37) and [RecipeSlot](https://github.com/mezz/JustEnoughItems/blob/1.18/Common/src/main/java/mezz/jei/common/gui/ingredients/RecipeSlot.java#L145-L150).

**Comment by mezz** [comment]
Thank you!
Can you remove the highlight code from `RecipeSlots#draw` and remove the `int highlightColor, int recipeMouseX, int recipeMouseY` parameters as well?

**Comment by vfyjxf** [comment]
> Thank you! Can you remove the highlight code from `RecipeSlots#draw` and remove the `int highlightColor, int recipeMouseX, int recipeMouseY` parameters as well?

Ok,I have removed the highlight code

**Comment by mezz** [comment]
Thank you for contributing!

**Pull request merged**
