### PR TITLE
Add a hook for getting the hovered ingredient in the recipe gui

### LINKED ISSUE #1357: API suggestion - a way to get the hovered item in recipe GUI
I was looking for a way to get the currently hovered item from the recipe GUI. Sadly, [the IRecipesGui interface](mezz/JustEnoughItems/blob/f5acb392ccdbc5ed8b6de6181f30bf0e42442957/src/api/java/mezz/jei/api/IRecipesGui.java), the only interface in the public API that the recipe GUI implements, does not have a way to get the currently hovered item like the [IIngredientListOverlay](https://github.com/mezz/JustEnoughItems/blob/f5acb392ccdbc5ed8b6de6181f30bf0e42442957/src/api/java/mezz/jei/api/IIngredientListOverlay.java#L19) does. 
This is definitely possible if I use JEI internals, but that might not work at all in a few versions.

*Use case*: I reimplemented Botania's Corporea request keybind (press a button when hovering over and item to request it from a nearby Corporea Index, see Vazkii/Botania#2668), but sadly this can't be used when in the recipe GUI. I was thinking about this when making that PR, but I only decided I really want it when I actually made use of this feature in a playthrough and couldn't request some crafting ingredients easily.

### PR DESCRIPTION
**Pull request by Hubry**
Resolves #1357. The hook is simple, just wrapping the existing internal method that takes position arguments to avoid copying the logic. I hope the version bump was appropriate, seems like the few PRs done in the past that extended the API did that, so...

### CODE REVIEW

**Comment by mezz** [comment]
Looks perfect, thanks for contributing!
Have you tested this with your mod? I have struggled a lot with mouse position in guis not being where I expect, so I'd like to see confirmation that it's working as expected.

**Comment by Hubry** [comment]
All testing I did so far was using debug mode, but I'm gonna give it a try with the actual use I had in mind.

**Comment by Hubry** [comment]
I tested it with my Botania dev enviroment on all GUI scales and it seems to be working perfectly.
("your mod" it is not really my mod, just contributing a bit :P )

**Comment by mezz** [comment]
Cool, sounds good to me.

**Pull request merged**
